### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Phatcat** [Phatcat/mangos-classic#5]
Hey @Grz3s, it was as I said, I won't even be able to help you on wotlk-db since the ban is organization-wide and since wotlk-db is under the cmangos organization I can no longer edit any of my already open PRs or issues and I can't make any new comments or open any more PRs, not on any core repo, not on any db repo...

I certainly hope we won't become strangers. You can still find me on the Rizon network under my regular name, just not in the cmangos channel. Hit me up anytime for any reason, mate.

**Comment by Grz3s** [comment]
```quote
I certainly hope we won't become strangers
```
I see no reason for that ;)

**Comment by Phatcat** [comment]
I did also mean you could find me on the Rizon channel, but perhaps we should find an alternative way of communication as well since it seems we've missed each other on a few occassions (i blame my client), something like facebook or discord or anything really, this IRC thing doesn't seem to be working too well, at least not for me ;)

Feel free to friend request me or just send a message my way facebook at least; https://www.facebook.com/HolstHein

**Comment by Grz3s** [comment]
i'm not a friend of FB.. twitshits etc... 
We can always discuss here if u want ofc ;)

**Comment by Phatcat** [comment]
Of course you aren't... xD

You could then add me on discord if you're not not a friend of theirs ^^

Phatcat #2556
